### PR TITLE
External Secret Operator Documentation

### PR DESCRIPTION
**Pull request by bilalbokharee**

### CODE REVIEW

**Comment by stakater-user** [comment]
@bilalbokharee Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-252-af126df4`

**Comment by stakater-user** [comment]
@bilalbokharee Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-252-9a684d84`

**Review by hanzala1234 — APPROVED** [review]

**Comment by stakater-user** [comment]
@bilalbokharee Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-252-820c9e70`

**Comment by stakater-user** [comment]
@bilalbokharee Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-252-0d96833a`

**Comment by stakater-user** [comment]
@hanzala1234 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.190`

**Pull request merged**
