### PR TITLE
Create Grafana Dashboard Guide

### PR DESCRIPTION
**Pull request by MichaelLi202112**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MichaelLi202112 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-249-368dd802`

**Comment by stakater-user** [comment]
@MichaelLi202112 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-249-4ddff790`

**Comment by stakater-user** [comment]
@ufateh Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-249-1cfd5cd6`

**Review by callum-stakater — DISMISSED** [review]
nice!

**Comment by rasheedamir** [comment]
@MichaelLi202112 we need to add it to the menu items as well

**Comment by MichaelLi202112** [comment]
> @MichaelLi202112 we need to add it to the menu items as well

Done

**Comment by stakater-user** [comment]
@MichaelLi202112 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-249-ba948fd3`

**Review by rasheedamir — APPROVED** [review]

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.191`

**Pull request merged**
