### PR TITLE
add introduction and maturity model to monitoring section

### PR DESCRIPTION
**Pull request by rasheedamir**
add introduction and maturity model to monitoring section

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-212-f03f9c0f`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/7e66d0f7fc1f87e2b0fb0d3773337670f5288068/checks) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-212-f6d554fc`

**Review by hanzala1234 — DISMISSED** [review]

**Comment by hanzala1234** [comment]
missing entry in config.js file

**Comment by rasheedamir** [comment]
@hanzala1234 added now

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-212-7b2acfd8`

**Review by hanzala1234 — APPROVED** [review]

**Comment by stakater-user** [comment]
@hanzala1234 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.151`

**Pull request merged**
