### PR TITLE
Add tenant operator changelog

### PR DESCRIPTION
**Pull request by ShahidHussain-srti**

### CODE REVIEW

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-267-523786e9`

**Comment by rasheedamir** [comment]
@LilShah shouldn't we differentiate between bugs and enhancements?

**Comment by ShahidHussain-srti** [comment]
@rasheedamir updated, please check

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-267-ce8016b1`

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-267-8febd5ff`

**Review by MuneebAijaz — APPROVED** [review]
LGTM

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.204`

**Pull request merged**
