### PR TITLE
Updated quota docs

### PR DESCRIPTION
**Pull request by MuneebAijaz**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MuneebAijaz Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-256-b8447289`

**Review by abdulhaseeb2 — APPROVED** [review]
lgtm

**Comment by stakater-user** [comment]
@MuneebAijaz Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-256-911d7974`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.194`

**Pull request merged**
