### PR TITLE
create place holder for backup and restore

### PR DESCRIPTION
**Pull request by rasheedamir**
create a place holder for backup and restore

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-7-1`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-7-2`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-7-3`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-7-4`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-7-5`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Pull request merged**
