### PR TITLE
Update TO changelog according to new releases' features

### PR DESCRIPTION
**Pull request by MuneebAijaz**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MuneebAijaz Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-275-ee0c986c`

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-275-2383cc74`

**Review by abdulhaseeb2 — APPROVED** [review]

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-275-533cb71d`

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-275-88c4e016`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.211`

**Pull request merged**
