### PR TITLE
Add nexus usage document

### PR DESCRIPTION
**Pull request by josedev-union**

### CODE REVIEW

**Comment by stakater-user** [comment]
@josedev-union Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-67-1`

**Review by rasheedamir — CHANGES_REQUESTED** [review]
you need to add here as well: https://github.com/stakater/StakaterCloudDocs/blob/master/.vuepress/config.js

so, it shows up in the menu

**Comment by ahmedwaleedmalik** [comment]
@josedev-union Can you please update this ?

**Comment by ahmedwaleedmalik** [comment]
Closing this PR. Please create a new PR with functional changes !

**Pull request closed without merging**
