### PR TITLE
Adding sonarqube upgrade documentation

### PR DESCRIPTION
**Pull request by Muneebstakater**

### CODE REVIEW

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/c113cac9ef4e7768f2c58b612ba9732f11ff6970/checks) has Failed!

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/89c0445e76e3b40c4fe538c53ad934383d71eb4f/checks) has Failed!

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-271-7d87b539`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-271-01c0faf1`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-271-48a28329`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-271-665fc223`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-271-7c231bad`

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.209`

**Pull request merged**
