### PR TITLE
replace images

### PR DESCRIPTION
**Pull request by rasheedamir**

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-37-5`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-37-1`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.stakater.com/job/Stakater/job/StakaterCloudDocs/job/PR-37/2/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-37-7`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-37-6`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-37-4`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-37-3`

**Review by hazim1093 — APPROVED** [review]

**Pull request merged**
