### PR TITLE
[SA-675] Update ArgoCD docs in Tenant Operator

### PR DESCRIPTION
**Pull request by ShahidHussain-srti**

### CODE REVIEW

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-264-d7833bf4`

**Comment by rasheedamir** [comment]
@LilShah plz add full blown example of AppProject so, it's clear how will look like

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-264-ab48a952`

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-264-e3976b3f`

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-264-86e53587`

**Review by MuneebAijaz — APPROVED** [review]
LGTM

**Comment by stakater-user** [comment]
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.201`

**Pull request merged**
