### PR TITLE
Add autoscaling with gitOps

### PR DESCRIPTION
**Pull request by faizanahmad055**
Signed-off-by: faizanahmad055 <faizan.ahmad55@outlook.com>

### CODE REVIEW

**Comment by stakater-user** [comment]
@faizanahmad055 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-126-3aa82fd4`

**Comment by stakater-user** [comment]
@faizanahmad055 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-126-9d75c859`

**Review by rasheedamir — APPROVED** [review]

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-126-6e952ea1`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.73`

**Pull request merged**
