### PR TITLE
add faqs section

### PR DESCRIPTION
**Pull request by rasheedamir**
add section of FAQ's

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-1`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-2`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-3`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-4`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-5`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-6`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-7`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-8`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-9`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-10`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-11`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-12`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-13`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-14`

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build 15](https://jenkins-delivery.stakater.com/job/Stakater/job/StakaterCloudDocs/job/PR-28/15/) has Failed!

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-16`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-28-17`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
